package com.kirabium.relayance.data.dto

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.Date

/**
 * Data Transfer Object (DTO) representing a customer entity in the database.
 *
 * This class is used by Room to map the "customers" table.
 *
 * @property id The unique identifier of the customer (auto-generated).
 * @property name The name of the customer.
 * @property email The email address of the customer.
 * @property createdAt The date when the customer was created (default: current date).
 */
@Entity(tableName = "customers")
data class CustomerDto(

    /**
     * The unique identifier for the customer.
     * This value is auto-generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int,

    /**
     * The name of the customer.
     */
    @ColumnInfo(name = "name")
    val name: String,

    /**
     * The email address of the customer.
     */
    @ColumnInfo(name = "email")
    val email: String,

    /**
     * The creation date of the customer record.
     * Defaults to the current date if not provided.
     */
    @ColumnInfo(name = "created_At")
    val createdAt: Date = Date()
)
